# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/info/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/info/
Content-Type: application/json
Authorization: Token fb91550c85b65f7eb9148fc07941b4a14f56bc7d

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/info/1/
Content-Type: application/json
Authorization: Token fb91550c85b65f7eb9148fc07941b4a14f56bc7d

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/info/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/info/?created_at_before=2026-10-01
Content-Type: application/json
